/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.prefs.Preferences;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import org.example.view.MainWindow;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

public class App {
    private static boolean darkMode = true; // Tema padrão: Dark

    public static void main(String[] args) {

        // Carrega a preferência salva
        Preferences prefs = Preferences.userNodeForPackage(App.class);
        darkMode = prefs.getBoolean("DARK_MODE", true); // Default: Dark
        FlatLaf.registerCustomDefaultsSource("themes");
        // Aplica o tema inicial
        atualizarTemaGlobal(darkMode);

        // Cria e exibe a janela principal
        SwingUtilities.invokeLater(() -> {
            MainWindow slaveMDIFrame = new MainWindow();
            slaveMDIFrame.start();
        });
    }

    // Método estático para trocar o tema (acessível de qualquer lugar)
    public static void atualizarTemaGlobal(boolean isDarkMode) {
        try {
            darkMode = isDarkMode;
            Preferences prefs = Preferences.userNodeForPackage(App.class);
            prefs.putBoolean("DARK_MODE", darkMode);
            if (isDarkMode) {
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
            } else {
                UIManager.setLookAndFeel(new FlatMacLightLaf());

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Getter para o tema atual
    public static boolean isDarkMode() {
        return darkMode;
    }
}
