/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.UIManager;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.prefs.Preferences;
import javax.swing.SwingUtilities;

public class App {
    private static boolean darkMode = true; // Tema padrão: Dark

    public static void main(String[] args) {
        // Carrega a preferência salva
        Preferences prefs = Preferences.userNodeForPackage(App.class);
        darkMode = prefs.getBoolean("DARK_MODE", true); // Default: Dark
        // Aplica o tema inicial
        atualizarTemaGlobal(darkMode);

        // Cria e exibe a janela principal
        SwingUtilities.invokeLater(() -> {
            MainMDIFrame mainFrame = new MainMDIFrame();
            mainFrame.setVisible(true);
        });
    }

    // Método estático para trocar o tema (acessível de qualquer lugar)
    public static void atualizarTemaGlobal(boolean isDarkMode) {
        try {
            darkMode = isDarkMode;
            Preferences prefs = Preferences.userNodeForPackage(App.class);
            prefs.putBoolean("DARK_MODE", darkMode);
            if (isDarkMode) {
                UIManager.setLookAndFeel(new FlatDarkLaf());
            } else {
                UIManager.setLookAndFeel(new FlatLightLaf());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Getter para o tema atual
    public static boolean isDarkMode() {
        return darkMode;
    }
}
