/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.example;

/**
 *
 * @author faber222
 */
public class ChildFrame extends javax.swing.JPanel {

    /**
     * Creates new form ChildFrame
     */
    public ChildFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTwibi = new javax.swing.JButton();
        jButtonWiforce = new javax.swing.JButton();
        jButtonAps = new javax.swing.JButton();
        jButtonRadios = new javax.swing.JButton();
        jButtonSwitchs = new javax.swing.JButton();
        jButtonOlts = new javax.swing.JButton();
        jLabelTwibi = new javax.swing.JLabel();
        jLabelWiforce = new javax.swing.JLabel();
        jLabelAps = new javax.swing.JLabel();
        jLabelRadios = new javax.swing.JLabel();
        jLabelSwitchs = new javax.swing.JLabel();
        jLabelOlts = new javax.swing.JLabel();

        jButtonTwibi.setText("Twibi");
        jButtonTwibi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwibiActionPerformed(evt);
            }
        });

        jButtonWiforce.setText("Wiforce");
        jButtonWiforce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWiforceActionPerformed(evt);
            }
        });

        jButtonAps.setText("Aps");

        jButtonRadios.setText("Radios");

        jButtonSwitchs.setText("Switchs");

        jButtonOlts.setText("Olts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getRootPane());
        getRootPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonWiforce, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonTwibi, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAps, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRadios, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonOlts, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSwitchs, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTwibi)
                                        .addComponent(jLabelWiforce)
                                        .addComponent(jLabelAps)
                                        .addComponent(jLabelRadios)
                                        .addComponent(jLabelSwitchs)
                                        .addComponent(jLabelOlts))
                                .addContainerGap(293, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonTwibi)
                                                        .addComponent(jLabelTwibi))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonWiforce)
                                                        .addComponent(jLabelWiforce))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonAps)
                                                        .addComponent(jLabelAps))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonRadios)
                                                        .addComponent(jLabelRadios))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonSwitchs))
                                        .addComponent(jLabelSwitchs))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonOlts)
                                        .addComponent(jLabelOlts))
                                .addContainerGap(22, Short.MAX_VALUE)));

        jButtonTwibi.putClientProperty("JButton.buttonType", "roundRect"); // Botão redondo

        // pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTwibiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonTwibiActionPerformed
        jLabelTwibi.setText("Check-List-Twibi");
        jLabelAps.setText("");
        jLabelOlts.setText("");
        jLabelRadios.setText("");
        jLabelSwitchs.setText("");
        jLabelWiforce.setText("");
    }// GEN-LAST:event_jButtonTwibiActionPerformed

    private void jButtonWiforceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonWiforceActionPerformed
        jLabelTwibi.setText("");
        jLabelAps.setText("");
        jLabelOlts.setText("");
        jLabelRadios.setText("");
        jLabelSwitchs.setText("");
        jLabelWiforce.setText("Check-List-Wiforce");
    }// GEN-LAST:event_jButtonWiforceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAps;
    private javax.swing.JButton jButtonOlts;
    private javax.swing.JButton jButtonRadios;
    private javax.swing.JButton jButtonSwitchs;
    private javax.swing.JButton jButtonTwibi;
    private javax.swing.JButton jButtonWiforce;
    private javax.swing.JLabel jLabelAps;
    private javax.swing.JLabel jLabelOlts;
    private javax.swing.JLabel jLabelRadios;
    private javax.swing.JLabel jLabelSwitchs;
    private javax.swing.JLabel jLabelTwibi;
    private javax.swing.JLabel jLabelWiforce;
    // End of variables declaration//GEN-END:variables
}
