/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author faber222
 */
public class MainMDIFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMDIFrame
     */
    public MainMDIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jToggleButton = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivos = new javax.swing.JMenu();
        jMenuItemNovo = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuTema = new javax.swing.JMenu();
        jMenuItemClaro = new javax.swing.JMenuItem();
        jMenuItemEscuro = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHECK-LIST-INTELBRAS");

        jToggleButton.setText("TEMA");
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        desktopPane.setLayer(jToggleButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
                desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                                .addContainerGap(879, Short.MAX_VALUE)
                                .addComponent(jToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        desktopPaneLayout.setVerticalGroup(
                desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(532, Short.MAX_VALUE)));

        jMenuArquivos.setText("Arquivo");

        jMenuItemNovo.setText("Novo");
        jMenuItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuItemNovo);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivos);

        jMenuTools.setText("Aparencia");

        jMenuTema.setText("Tema");

        jMenuItemClaro.setText("Claro");
        jMenuItemClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClaroActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuItemClaro);

        jMenuItemEscuro.setText("Escuro");
        jMenuItemEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEscuroActionPerformed(evt);
            }
        });
        jMenuTema.add(jMenuItemEscuro);

        jMenuTools.add(jMenuTema);

        jMenuBar1.add(jMenuTools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemNovoActionPerformed
        ChildFrame childFrame = new ChildFrame();
        desktopPane.add(childFrame);
        childFrame.putClientProperty("JInternalFrame.dropShadow", true); // Sombra
        childFrame.setVisible(true);
    }// GEN-LAST:event_jMenuItemNovoActionPerformed

    private void jMenuItemClaroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemClaroActionPerformed
        App.atualizarTemaGlobal(false);
        atualizarUI(); // Atualiza a interface
    }// GEN-LAST:event_jMenuItemClaroActionPerformed

    private void jMenuItemEscuroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemEscuroActionPerformed
        App.atualizarTemaGlobal(true);
        atualizarUI(); // Atualiza a interface
    }// GEN-LAST:event_jMenuItemEscuroActionPerformed

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButtonActionPerformed
        App.atualizarTemaGlobal(!App.isDarkMode());
        atualizarUI();
    }// GEN-LAST:event_jToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMDIFrame().setVisible(true);
            }
        });
    }

    public void start() {
        new MainMDIFrame().setVisible(true);
    }

    // Método para atualizar todos os componentes
    private void atualizarUI() {
        SwingUtilities.updateComponentTreeUI(this); // Atualiza o JFrame principal
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            SwingUtilities.updateComponentTreeUI(frame); // Atualiza janelas internas
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuArquivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemClaro;
    private javax.swing.JMenuItem jMenuItemEscuro;
    private javax.swing.JMenuItem jMenuItemNovo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuTema;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JToggleButton jToggleButton;
    // End of variables declaration//GEN-END:variables
}
